config/routes.rb
Rails.application.routes.draw do
  get("/", to: "welcome#home", as: :root)
  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :clients do
    post("/call", to: "clients#call")
    resources :policies #do
      # resources :coverages, except: [:show]
     #end
  end

  resources :policies, only: [] do
    resources :payments, only: [:new, :create]
   end

  resources :tokens, only: [:create]
  
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      
      resource :session, only: [:create, :destroy]

      resources :clients do
        post("/call", to: "clients#call")
      end

      resources :users, only:[] do
        get :current, on: :collection
      end

      resources :users

      resources :policies, only: [] do
        resources :payments, only: [:new, :create]
       end
    
      resources :tokens, only: [:create]
    end
  end
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :policies, dependent: :destroy
    validates :email,
    presence: true, 
    uniqueness: true, 
    format: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    after_validation :geocode

    def full_name
        "#{first_name} #{last_name}".strip
    end

    def full_address
        [street_address, city, province, postal_code].compact.join(', ')
    end

    geocoded_by :full_address
end

app/controllers/api/v1/clients_controller.rb
class Api::V1::ClientsController < Api::ApplicationController
    before_action :authenticate_user!
    def index
        clients = Client.all.order(created_at: :desc)
        render json: clients
    end

    def show
        render json: client
    end

    def create
        client = Client.new(client_params)
        client.user_id = current_user.id

      if client.save!
        # will show attributes specified in the client_serializer
         render json: client
      else
        render json: {errors: client.errors, status: 422 }
      end
    end

    def destroy
      client.destroy
      render json:{status: 200}, status: 200
    end

    def call
      # render json: params
        @client = Client.find params[:client_id]
        client = Twilio::REST::Client.new ENV["TWILIO_ACCOUNT_SID"], ENV["TWILIO_AUTH_TOKEN"]
        call = client.calls.create(
          to:   @client.phone_number,
          from: ENV["TWILIO_PHONE_NUMBER"],
          url: "https://example.herokuapp.com/connect/#{ENV["TWILIO_PHONE_NUMBER"]}"
        )
    end

    private
    def client
        @client ||= Client.find params[:id]
    end

    def client_params
        params.require(:client).permit(:first_name,
        :last_name,
        :phone_number,
        :email,
        :street_address,
        :city,
        :province,
        :postal_code,
        :marketing_consent)
      end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all.order(created_at: :desc)
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @policies = @client.policies.order(created_at: :desc)
    @firehalls = FireHall.all

    if @client.geocoded?
      closest = Float::INFINITY
      @firehall_closest
      @firehall_near = []
      @firehall_close = []
      @firehall_far = []

      @firehalls.each do |hall|
        if hall.distance_to([@client.latitude, @client.longitude], :km) < closest
          closest = hall.distance_to([@client.latitude, @client.longitude], :km)
          @firehall_closest = hall
        end

        if hall.distance_to([@client.latitude, @client.longitude], :km) <= 2.5
          @firehall_near << hall
        elsif hall.distance_to([@client.latitude, @client.longitude], :km) > 2.5 && hall.distance_to([@client.latitude, @client.longitude], :km) < 5
          @firehall_close << hall
        elsif hall.distance_to([@client.latitude, @client.longitude], :km) >= 5
          @firehall_far << hall
        end
      end
    end
    
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    @client.user_id = current_user.id
    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client record was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client record was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def call
    # render json: params
      @client = Client.find params[:client_id]
      client = Twilio::REST::Client.new ENV["TWILIO_ACCOUNT_SID"], ENV["TWILIO_AUTH_TOKEN"]
      call = client.calls.create(
        to:   @client.phone_number,
        from: ENV["TWILIO_PHONE_NUMBER"],
        url: "https://example.herokuapp.com/connect/#{ENV["TWILIO_PHONE_NUMBER"]}"
      )

      respond_to do |format|
        format.html { redirect_to @client, notice: 'Call in progress!' }
      end
  end

  def connect
    response = Twilio::TwiML::VoiceResponse.new do |r|
      r.say('Thanks for contacting our sales department. Our '\
        'next available representative will take your call.', voice: 'alice')
      r.dial number: Rails.application.credentials.twilio_contact
    end
    render xml: response.to_s
  end

  private
    def set_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:first_name,
      :last_name,
      :phone_number,
      :email,
      :street_address,
      :city,
      :province,
      :postal_code,
      :marketing_consent)
    end
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>
      <ul>
        <% client.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <div class="form-group">
      <div class="form-row">
        <div class = "col-md-6 mb-3">
          <%=f.label :first_name%>
          <%=f.text_field :first_name, class: "form-control", placeholder: "John"%>
        </div>
        <div class = "col-md-6 mb-3">
          <%=f.label :last_name%>
          <%=f.text_field :last_name, class: "form-control", placeholder: "Doe"%>
        </div>
      </div>
      <div class = "form-row">
        <div class = "col-md-6 mb-3">
          <%=f.label :phone_number%>
          <%=f.text_field :phone_number, class: "form-control", placeholder: "123-456-7890"%>
        </div>
        <div class = "col-md-6 mb-3">
          <%=f.label :email%>
          <%=f.email_field :email, class: "form-control", placeholder: "jdoe@example.com"%>
        </div>
      </div>
      <div class = "form-row">
        <div class = "col-md-6 mb-3">
          <%=f.label :street_address%>
          <%=f.text_field :street_address, class: "form-control"%>
        </div>
        <div class = "col-md-6 mb-3">
          <%=f.label :city%>
          <%=f.text_field :city, class: "form-control"%>
        </div>
      </div>
      <div class = "form-row">
        <div class = "col-md-3 mb-3">
          <%=f.label :province%>
          <%=f.select :province, ['AB', 'BC', 'SK', 'MB','QC','ON','NL','NS','PEI','YT','NT', 'NU'], class: "form-control"%>
        </div>
        <div class = "col-md-12 mb-3">
          <%=f.label :postal_code%>
          <%=f.text_field :postal_code, class: "form-control", placeholder: "A1A 1A1"%>
        </div>
      </div>
      <div>
        <%= f.check_box :marketing_consent, {}, "true", "false" %>
        <%= f.label :marketing_consent, "Has the client agreed to receive marketing materials and acknowledged that they may opt out at any time?" %>
      </div>
      <br>
      <%= f.submit class:"btn btn-primary"%>
      <%= link_to 'Cancel', 'javascript:history.back()', data:{confirm: "All changes will not be saved. Are you sure?"}, class:"btn btn-warning" %>
    </div>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>
<%= render 'form', client: @client %>

app/views/clients/index.html.erb
<%= stylesheet_link_tag 'index' %>
<p id="notice"><%= notice %></p>
<div>
  <div>
    <h1> Clients </h1>
    <form class="form-inline md-form form-sm">
      <input class="form-control form-control-sm mr-4 w-25 float-right" type="text" placeholder="Lookup Client..." aria-label="Search">
      <span>
        <%= link_to 'Add Client Profile', new_client_path, class:"btn btn-sm btn-success float-right" %>
      </span>
    </form>
  </div>
  <br>
  <div>
    <table>
      <tr id="table-header">
        <td>Name</td>
        <td>Phone Number</td>
        <td>Email</td>
      </tr>
      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <td><%= link_to client.full_name, client %></td>
            <td><%= client.phone_number %></td>
            <td>
              <%= client.email %>
              <td>
                <%= link_to 'Show More Detail', client, class:"btn-sm btn-info" %>
                <%= link_to 'Delete Record', client, method: :delete, data: { confirm: 'This action will permanently delete this entry. Are you sure?' }, class:"btn-sm btn-danger" %>
              </td>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/clients/new.html.erb
<h1>New Client</h1>
<%= render 'form', client: @client %>

app/views/clients/show.html.erb
<%= stylesheet_link_tag 'client_show' %>
<p id="notice"><%= notice %></p>
<div class = "card">
  <div class="card-header">
    <h2><%=@client.full_name%>'s Details</h2>
  </div>
  <div class="card-body">
    <table>
      <tr>
        <td><strong> Phone Number: </strong></td>
        <td><%= link_to @client.phone_number, client_call_path(@client), method: :post %></td>
        <td><strong>Email:</strong> </td>
        <td colspan="2"><%= @client.email %></td>
      </tr>
      <tr>
        <td><strong>Street Address:</strong> </td>
        <td><%= @client.street_address %> </td>
        <td><strong>City:</strong></td>
        <td><%= @client.city %></td>
        <td><strong>Postal Code:</strong> </td>
        <td style="margin-left: 5px"><%= @client.postal_code %> </td>
      </tr>
      <tr>
        <td><strong>Marketing Consent:</strong> </td>
        <% if @client.marketing_consent? %>
          <td colspan="4"> Client May Be Contacted About New Products and Offerings </td>
        <% else %>
          <td colspan="4"> Client Does Not Wish to be Contacted About New Products and Offerings </td>
        <% end %>
      </tr>
    </table>
    <br>
    <%= link_to 'Edit Client Details', edit_client_path(@client), class: "btn-sm btn-warning" %>
    <%= link_to 'Back to Client Directory', clients_path, class: "btn-sm btn-success" %>
  </div>
</div>
<br>
<div class= "card" id="map-container">
  <div class="card-header">
    <h2>Factors Affecting Quote</h2>
  </div>
  <div class="card-body">
    <div id="map">
      <% unless @client.geocoded?%>
        <h5 id="geocode-error">
          Client address could not be located. Please check address input. 
        </h5>
      <% end %>
    </div>
    <div id= "map-controls">
      <span>
        <input type="checkbox" name="neighbourhoods" id="neighbourhoods"> <label for="neighbourhoods"> Neighbourhood Boundaries </label>
      </span>
      <span>
        <input type="checkbox" name="fire_halls" id="fire_halls"> <label for="fire_halls"> Fire Hall Proximity </label>
      </span>
      <span>
        <input type="checkbox" name="fire_hydrants" id="fire_hydrants"> <label for="fire_hydrants"> Fire Hydrant Proximity </label>
      </span>
    </div>
    <br>
    <%if @client.geocoded? %>
      <button id="firehall-details">Fire Hall Details</button>
      <br>
      <br>
      <div id="firehall-list" hidden>
        <h3>Fire Hall Locations</h3>
        <strong> 
          <p>The closest fire hall is Fire Hall <%= @firehall_closest.fire_hall_name%> located at <%= @firehall_closest.address %>, approximately <%= @firehall_closest.distance_to([@client.latitude, @client.longitude], :km).round(1)%>kms away</p>
        </strong>
        <p id="near"><strong> Within 2.5kms </strong></p>
        <p>
          <ul>
            <%@firehall_near.each do |hall|%>
              <li>
                Fire Hall <%= hall.fire_hall_name%>: <%= hall.address%>
                <ul>
                  <li><%= (hall.distance_to([@client.latitude, @client.longitude], :km)).round(1) %>kms away</li>
                </ul>
              </li>
            <% end %>
          </ul>
        </p>
        <p id="close"><strong> Within 5.0kms </strong></p>
        <p>
          <ul>
            <%@firehall_close.each do |hall|%>
              <li>
                Fire Hall <%= hall.fire_hall_name%>: <%= hall.address%>
                <ul>
                  <li><%= (hall.distance_to([@client.latitude, @client.longitude], :km)).round(1) %>kms away</li>
                </ul>
              </li>
            <% end %>
          </ul>
        </p>
        <p id="far"><strong> More than 5kms </strong></p>
        <p>
          <ul>
            <%@firehall_far.each do |hall|%>
              <li>
                Fire Hall <%= hall.fire_hall_name%>: <%= hall.address%>
                <ul>
                  <li><%= (hall.distance_to([@client.latitude, @client.longitude], :km)).round(1) %>kms away</li>
                </ul>
              </li>
            <% end %>
          </ul>
        </p>
      </div>
    <% else %>
      <h5 id="geocode-error">
        Firehall info could not be retrieved. Please ensure client's address is correct.
      </h5>
    <% end %>
  </div>
</div>
<br>
<div class="card">
  <div class="card-header">
    <h2>Existing Policies</h2>
  </div>
  <div class="card-body">
    <%= link_to 'Add a Policy', new_client_policy_path(@client), class: "btn-sm btn-success" %>
    <div>
      <br>
      <% @policies.each do |policy| %>
        <div class="card">
          <div class="card-body">
            <p>Policy Number: <%= policy.policy_number%></p>
            <p>Policy Premium: <%= number_to_currency(policy.annual_premium, {precision: 2})%></p>
            <%= link_to 'Edit Policy', edit_client_policy_path(@client.id, policy.id), class: "btn-sm btn-warning" %>
            <%= link_to 'Delete Policy', client_policy_path(@client.id, policy.id), method: :delete, class: "btn-sm btn-danger" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<script>
  let map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: new google.maps.LatLng(<%= @client.latitude %>, <%= @client.longitude %>),
      zoom: 15,
      mapTypeId: 'terrain'
    });
  
    let marker = new google.maps.Marker({
          map: map,
          position: map.center,
          animation: google.maps.Animation.DROP
        });
  
    let clientInfoWindow = new google.maps.InfoWindow({
      content: '<div><strong><%= @client.full_name%></strong><div> <%= @client.full_address%>'
      });
      marker.addListener('click', function() {
        clientInfoWindow.open(map, marker);
      });
  
    let neighbourhoods = 'https://data.vancouver.ca/download/kml/cov_localareas.kml';
    let neighbourhoodLayer = new google.maps.KmlLayer(neighbourhoods, {
          suppressInfoWindows: true,
          preserveViewport: true,
      });
  
    let fireHydrants = 'http://data.vancouver.ca/download/kml/water_hydrants.kmz';
    let hydrantLayer = new google.maps.KmlLayer(fireHydrants, {
          suppressInfoWindows: true,
          preserveViewport: true
      });
  
    function generateKML(layer){
      layer.setMap(map)
    }
  
    function removeKML(layer){
      layer.setMap(null)
    }
  
  document.querySelector("#neighbourhoods").addEventListener("change", () => {
      if(document.querySelector("#neighbourhoods").checked == true){
        generateKML(neighbourhoodLayer);
      } else if(document.querySelector("#neighbourhoods").checked == false){
        removeKML(neighbourhoodLayer);
      }
    })
  
  document.querySelector("#fire_hydrants").addEventListener("change", () => {
      if(document.querySelector("#fire_hydrants").checked == true){
        generateKML(hydrantLayer);
      } else if(document.querySelector("#fire_hydrants").checked == false){
        removeKML(hydrantLayer);
      }
    })
  }
  
  let markerArray = [];
  function fireHallMarkers(props){
    let marker = new google.maps.Marker({
      map: map,
      position: props.coords,
      icon: '/assets/fire-station.svg',
      animation: google.maps.Animation.DROP
    });
  
    let fireHallInfoWindow = new google.maps.InfoWindow({
    content: props.content,
    address: props.address
    });
  
    marker.addListener('click', function() {
      fireHallInfoWindow.open(map, marker);
    });
    markerArray.push(marker);
    }
  
  document.querySelector("#fire_halls").addEventListener("change", () => {
    let fireHallOrigins = [];
      <% @firehalls.each do |hall| %>
        fireHallOrigins.push({coords: {lat: <%= hall.to_coordinates.first %>, lng: <%=hall.to_coordinates.last%>}, content:'<div> <strong>Fire Hall <%= hall.fire_hall_name %> </strong><div/>' + '<div><%= hall.address %>, Vancouver, BC <div/>' + '<div>Located<strong> <%= (hall.distance_to([@client.latitude, @client.longitude], :km)).round(1) %>kms </strong> away<div/>' })
      <% end %>
  
    for(let i = 0; i < fireHallOrigins.length; i++){
      fireHallMarkers(fireHallOrigins[i]);
    }
  
    if(document.querySelector("#fire_halls").checked == false) {
      for (var i = 0; i < markerArray.length; i++) {
        markerArray[i].setMap(null);
        }
      };
    }
  );
  
  document.querySelector("#firehall-details").addEventListener("click", event => {
    let list = document.querySelector("#firehall-list");
    list.toggleAttribute('hidden');
  })
</script>
<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_MAPS_API_KEY']%>&callback=initMap"></script>