config/routes.rb
Rails.application.routes.draw do
  get("/", to: "welcome#home", as: :root)
  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :clients do
    post("/call", to: "clients#call")
    resources :policies #do
      # resources :coverages, except: [:show]
     #end
  end

  resources :policies, only: [] do
    resources :payments, only: [:new, :create]
   end

  resources :tokens, only: [:create]
  
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      
      resource :session, only: [:create, :destroy]

      resources :clients do
        post("/call", to: "clients#call")
      end

      resources :users, only:[] do
        get :current, on: :collection
      end

      resources :users

      resources :policies, only: [] do
        resources :payments, only: [:new, :create]
       end
    
      resources :tokens, only: [:create]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>CustomCrm</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137771782-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-137771782-1');
    </script>

    <script src="https://js.stripe.com/v3/"></script>
    <%= javascript_include_tag 'https://media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js' %>
    <%= javascript_include_tag 'https://media.twiliocdn.com/sdk/js/chat/v3.0/twilio-chat.min.js' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div id="background-container">
      <% if user_signed_in? %>
        <div class="container">
          <div class="row-fluid">
            <header id = "sidenav" class="span4">
              <%= stylesheet_link_tag 'navbar' %>
              <nav>
                <%= link_to image_tag('logo.svg', id: "logo"), root_path %>
                <ul>
                  <% if user_signed_in? %>
                    <li>
                      <%= link_to 'Employee Directory', users_path %>
                    </li>
                    <li>
                      <%= link_to 'Client Directory', clients_path %>
                    </li>
                    <li>
                      <%= link_to 'Sign Out', session_path, method: :delete%>
                    </li>
                  <% else %>
                    <li>
                      <%= link_to 'Sign In', new_session_path %>
                    </li>
                  <% end %>
                </ul>
              </nav>
            </header>
          <% end %>
          <section class="span8 m-4">
            <%= yield %>
          </section>
        </div>
      </div>
      <% if user_signed_in? %>
        <%= stylesheet_link_tag 'footer' %>
        <footer class="container">
          <div id="chat-container" class="fixed-bottom">
            <div id="chat-header">
              <h4>Chat</h4>
            </div>
            <div class="messages" hidden>
              <div class="message">
                <span class="user">User:</span> Let's chat!
              </div>
            </div>
            <form id="chat-input" hidden>
              <label for="message">Message:</label> <br>
              <input type="text-area" id="message" placeholder="Enter your message..." />
              <button type="submit" id="chat-button">Send</button>
            </form>
          </div>
        </footer>
      <% end %>
    </div>
  </body>
  <script>
    <% if user_signed_in? %>
      document.querySelector("#chat-header").addEventListener("click", () =>{
        let chatBody = document.querySelector(".messages");
        let chatInput = document.querySelector("#chat-input");
        chatBody.toggleAttribute("hidden");
        chatInput.toggleAttribute("hidden");
      })
    <% end %>
  </script>
</html>