config/routes.rb
Rails.application.routes.draw do
  get("/", to: "welcome#home", as: :root)
  resource :session, only: [:new, :create, :destroy]
  resources :users
  resources :clients do
    post("/call", to: "clients#call")
    resources :policies #do
      # resources :coverages, except: [:show]
     #end
  end

  resources :policies, only: [] do
    resources :payments, only: [:new, :create]
   end

  resources :tokens, only: [:create]
  
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      
      resource :session, only: [:create, :destroy]

      resources :clients do
        post("/call", to: "clients#call")
      end

      resources :users, only:[] do
        get :current, on: :collection
      end

      resources :users

      resources :policies, only: [] do
        resources :payments, only: [:new, :create]
       end
    
      resources :tokens, only: [:create]
    end
  end
end

app/models/policy.rb
class Policy < ApplicationRecord
    belongs_to :client
    has_many :coverages
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :set_policy, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /policies
  # GET /policies.json
  def index
    @policies = Policy.all
  end

  # GET /policies/1
  # GET /policies/1.json
  def show
  end

  # GET /policies/new
  def new
    @client = Client.find params[:client_id]
    @policy = Policy.new
  end

  # GET /policies/1/edit
  def edit
    @client = Client.find params[:client_id]
  end

  # POST /policies
  # POST /policies.json
  def create
    @client = Client.find params[:client_id]
    @policy = Policy.new(policy_params)
    @policy.client_id = @client.id

    respond_to do |format|
      if @policy.save
        # message = "Hi, #{@client.first_name}! A policy with policy # '#{@policy.policy_number}' was created under your account."
        # TwilioTextMessenger.new(message).call
        # redirect_to client_path(@client)
        format.html { redirect_to new_policy_payment_path(@policy), notice: 'Policy setup complete. Awaiting payment.' }
        format.json { render :show, status: :created, location: @policy }
      else
        format.html { render :new }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /policies/1
  # PATCH/PUT /policies/1.json
  def update
    respond_to do |format|
      if @policy.update(policy_params)
        message = "Hi, #{@policy.client.first_name}! Policy number '#{@policy.policy_number}' was recently updated. Please login to your account to see full details."
        phone_number = @policy.client.phone_number

        TwilioTextMessenger.new(message, phone_number).text_client

        format.html { redirect_to client_path(@policy.client), notice: 'Policy was successfully updated.'}
        format.json { render :show, status: :ok, location: @policy }
      else
        format.html { render :edit }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    @policy.destroy
    message = "Policy number '#{@policy.policy_number}' was removed from your account. Please login to your account to see full details."
    phone_number = @policy.client.phone_number
    
    TwilioTextMessenger.new(message, phone_number).text_client

    respond_to do |format|
      format.html { redirect_to client_url(@policy.client_id), notice: 'Policy was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_policy
      @policy = Policy.find(params[:id])
    end

    def policy_params
      params.fetch(:policy, {}).permit(:policy_number, :annual_premium, :start_date)
    end
end

app/views/policies/_form.html.erb
<%= stylesheet_link_tag 'client_show' %>
<%= form_with(model: [@client, @policy], local: true) do |f| %>
  <% if policy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(policy.errors.count, "error") %> prohibited this policy from being saved:</h2>
      <ul>
        <% policy.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
    <div class="form-group">
      <div class="form-row">
        <div class="col-md-6 mb-3">
          <%= f.label :policy_number, "Policy Number:"%>
          <%= f.text_field :policy_number, value: SecureRandom.hex(5), class: "form-control"%>
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-6 mb-3">
          <%= f.label :start_date%> <br>
          <%= select_date Date.today, prefix: :start_date, class: "form-control" %>
        </div>
      </div>
      <br>
      <table>
        <tr>
          <th> Coverage: </th>
          <th style="padding-left: 5px"> Limit: </th>
          <th style="padding-left: 5px"> Deductible: </th>
          <th style="padding-left: 5px"> Amount: </th>
        </tr>
        <tr>
          <th> Fire </th>
          <td style="padding-left: 5px"> <%= f.select :limit, ['$1,000,000', '$2,000,000', '$3,000,000', '$5,000,000', '$10,000,000'], class:"form-control"%> </td>
          <td style="padding-left: 5px">
            <%= f.select :limit, ['$500', '$1,000', '$1,500', '$2,500', '$5,000'], class:"form-control"%> </td>
          <td>
            $<%= f.number_field :limit, value: number_to_currency(rand(50.00..1_000.00), delimiter: '', unit: ''), step: 0.01, id:"amount"%>
          </td>
        </tr>
        <tr>
          <th> Water Damage </th>
          <th style="padding-left: 5px"> <%= f.select :limit, ['$1,000,000', '$2,000,000', '$3,000,000', '$5,000,000', '$10,000,000'], class:"form-control"%> </th>
          <td style="padding-left: 5px"> <%= f.select :limit, ['$500', '$1,000', '$1,500', '$2,500', '$5,000'], class:"form-control"%> </td>
          <td>
            $<%= f.number_field :limit, value: number_to_currency(rand(50.00..1_000.00), delimiter: '', unit: ''), step: 0.01, id:"amount"%>
          </td>
        </tr>
        <tr>
          <th style="padding-right: 5px" > Sewer Back Up </th>
          <th style="padding-left: 5px"> <%= f.select :limit, ['$1,000,000', '$2,000,000', '$3,000,000', '$5,000,000', '$10,000,000'], class:"form-control"%> </th>
          <td style="padding-left: 5px"> <%= f.select :limit, ['$500', '$1,000', '$1,500', '$2,500', '$5,000'], class:"form-control"%> </td>
          <td>
            $<%= f.number_field :limit, value: number_to_currency(rand(50.00..1_000.00), delimiter: '', unit: ''), step: 0.01, id:"amount"%>
          </td>
        </tr>
        <tr>
          <th> Earthquake </th>
          <th style="padding-left: 5px"> <%= f.select :limit, ['$1,000,000', '$2,000,000', '$3,000,000', '$5,000,000', '$10,000,000'], class:"form-control"%> </th>
          <td style="padding-left: 5px"> <%= f.select :limit, ['5%', '10%', '15%', '20%'], class:"form-control"%> </td>
          <td>
            $<%= f.number_field :limit, value: number_to_currency(rand(50.00..1_000.00), delimiter: '', unit: ''), step: 0.01, id:"amount"%>
          </td>
        </tr>
      </table>
      <br>
      <div class="form-row">
        <div class="col-md-6 mb-3">
          <%= f.label :annual_premium, "Estimated Annual Premium:"%> <br>
          <%= f.number_field :annual_premium, value: number_to_currency(rand(500.00..10_000.00), delimiter: '', unit: ''), step: 0.01, class:"form-control", id:"grand-total"%>
        </div>
      </div>
      <br>
      <div>
        <%= f.submit "Proceed to Payment", class:"btn btn-success", data: {confirm:"Are all coverage options correct?"}%>
        <%= link_to 'Cancel', 'javascript:history.back()', data:{confirm: "All changes will not be saved. Are you sure?"}, class:"btn btn-danger" %>
      </div>
    </div>
  <% end %>

app/views/policies/edit.html.erb
<h1>Editing Policy</h1>
<%= render 'form', policy: @policy %>

app/views/policies/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Policies</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @policies.each do |policy| %>
      <tr>
        <td><%= link_to 'Show', policy %></td>
        <td><%= link_to 'Edit', edit_policy_path(policy) %></td>
        <td><%= link_to 'Destroy', policy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Policy', new_policy_path %>

app/views/policies/new.html.erb
<h1>New Policy</h1>
<%= render 'form', policy: @policy %>

app/views/policies/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_policy_path(@policy) %> |
<%= link_to 'Back', policies_path %>